version: '3'

networks:
  front:
    driver: bridge

services:
  nginx:
    build:
      context: ./nginx
    image: nginx:latest
    volumes:
      - ../public:/var/www/public
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - front
    ports:
      - "80:80"
      - "443:443"

  php-fpm:
    build:
      context: ./php-fpm
    image: php-fpm:latest
    volumes:
      - ../src:/var/www/src
      - ../public:/var/www/public
    networks:
      - front

  mariadb:
    build:
      context: ./mariadb
    image: mariadb:latest
    restart: always
    env_file:
      - .mariadb.env
    networks:
      - front
    ports:
      - "13306:3306"
    volumes:
      - ./mariadb/init.d:/docker-entrypoint-init.d